modLoader="fabric"
loaderVersion="[>=0.16.5)"
license="AGPLV-3"
[[mods]]
modId="breakthemod"
version="1.0.0"
displayName="BreakTheMod"
description="Mod version of breakthebot."
logoFile="resources/assets/icon.png"  # Path to the icon relative to the JAR root
